; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
board = rpipicow
board_microros_transport = wifi
board_microros_distro = jazzy

[env:rpipicow]
board = rpipicow
board_microros_transport = wifi
board_microros_distro = jazzy
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	adafruit/Adafruit MPU6050@^2.2.9
	adafruit/Adafruit Unified Sensor@^1.1.15

[env:main_app]
board = rpipicow
board_microros_transport = wifi
board_microros_distro = jazzy
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	adafruit/Adafruit MPU6050@^2.2.9
	adafruit/Adafruit Unified Sensor@^1.1.15

[env:i2c_test]
board = ${env.board}
build_src_filter = -<*> +<i2c-scan.cpp>

[env:mpu_test]
board = ${env.board}
build_src_filter = -<*> +<mpu-6050-read.cpp>
lib_deps =
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit MPU6050@^2.2.9
